/**
 * Returns on the search page
 * Autogenerated with http://json2ts.com/
 *
 * @example link:
 * https://www.youtube.com/results?search_query=stopgame
 *
 * @example path to content:
 * json.contents.twoColumnSearchResultsRenderer.primaryContents.sectionListRenderer.contents[0].itemSectionRenderer.contents
 * */
export declare module SearchResultResponse {

    export interface Param {
        key: string;
        value: string;
    }

    export interface ServiceTrackingParam {
        service: string;
        params: Param[];
    }

    export interface MainAppWebResponseContext {
        loggedOut: boolean;
    }

    export interface YtConfigData {
        visitorData: string;
        rootVisualElementType: number;
    }

    export interface WebResponseContextExtensionData {
        ytConfigData: YtConfigData;
        hasDecorated: boolean;
    }

    export interface ResponseContext {
        serviceTrackingParams: ServiceTrackingParam[];
        mainAppWebResponseContext: MainAppWebResponseContext;
        webResponseContextExtensionData: WebResponseContextExtensionData;
    }

    export interface Title {
        simpleText: string;
    }

    export interface WebCommandMetadata {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata {
        webCommandMetadata: WebCommandMetadata;
    }

    export interface BrowseEndpoint {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata;
        browseEndpoint: BrowseEndpoint;
    }

    export interface Thumbnail2 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail {
        thumbnails: Thumbnail2[];
    }

    export interface Run {
        text: string;
        bold?: boolean;
    }

    export interface DescriptionSnippet {
        runs: Run[];
    }

    export interface WebCommandMetadata2 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata2 {
        webCommandMetadata: WebCommandMetadata2;
    }

    export interface BrowseEndpoint2 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata2;
        browseEndpoint: BrowseEndpoint2;
    }

    export interface Run2 {
        text: string;
        navigationEndpoint: NavigationEndpoint2;
    }

    export interface ShortBylineText {
        runs: Run2[];
    }

    export interface Run3 {
        text: string;
    }

    export interface VideoCountText {
        runs: Run3[];
    }

    export interface SubscriptionButton {
        subscribed: boolean;
    }

    export interface Icon {
        iconType: string;
    }

    export interface MetadataBadgeRenderer {
        icon: Icon;
        style: string;
        tooltip: string;
        trackingParams: string;
    }

    export interface OwnerBadge {
        metadataBadgeRenderer: MetadataBadgeRenderer;
    }

    export interface SubscriberCountText {
        simpleText: string;
    }

    export interface Run4 {
        text: string;
    }

    export interface Text {
        runs: Run4[];
    }

    export interface WebCommandMetadata3 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata3 {
        webCommandMetadata: WebCommandMetadata3;
    }

    export interface WebCommandMetadata4 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata4 {
        webCommandMetadata: WebCommandMetadata4;
    }

    export interface SearchEndpoint {
        query: string;
    }

    export interface NextEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata4;
        searchEndpoint: SearchEndpoint;
    }

    export interface SignInEndpoint {
        nextEndpoint: NextEndpoint;
        continueAction: string;
    }

    export interface NavigationEndpoint3 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata3;
        signInEndpoint: SignInEndpoint;
    }

    export interface ButtonRenderer {
        style: string;
        size: string;
        isDisabled: boolean;
        text: Text;
        navigationEndpoint: NavigationEndpoint3;
        trackingParams: string;
    }

    export interface SubscribeButton {
        buttonRenderer: ButtonRenderer;
    }

    export interface WebCommandMetadata5 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata5 {
        webCommandMetadata: WebCommandMetadata5;
    }

    export interface BrowseEndpoint3 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint4 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata5;
        browseEndpoint: BrowseEndpoint3;
    }

    export interface Run5 {
        text: string;
        navigationEndpoint: NavigationEndpoint4;
    }

    export interface LongBylineText {
        runs: Run5[];
    }

    export interface ChannelRenderer {
        channelId: string;
        title: Title;
        navigationEndpoint: NavigationEndpoint;
        thumbnail: Thumbnail;
        descriptionSnippet: DescriptionSnippet;
        shortBylineText: ShortBylineText;
        videoCountText: VideoCountText;
        subscriptionButton: SubscriptionButton;
        ownerBadges: OwnerBadge[];
        subscriberCountText: SubscriberCountText;
        subscribeButton: SubscribeButton;
        trackingParams: string;
        longBylineText: LongBylineText;
    }

    export interface Title2 {
        simpleText: string;
    }

    export interface Thumbnail4 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail3 {
        thumbnails: Thumbnail4[];
    }

    export interface Run6 {
        text: string;
    }

    export interface AccessibilityData {
        label: string;
    }

    export interface Accessibility {
        accessibilityData: AccessibilityData;
    }

    export interface Title3 {
        runs: Run6[];
        accessibility: Accessibility;
    }

    export interface Run7 {
        text: string;
        bold?: boolean;
    }

    export interface DescriptionSnippet2 {
        runs: Run7[];
    }

    export interface WebCommandMetadata6 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata6 {
        webCommandMetadata: WebCommandMetadata6;
    }

    export interface BrowseEndpoint4 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint5 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata6;
        browseEndpoint: BrowseEndpoint4;
    }

    export interface Run8 {
        text: string;
        navigationEndpoint: NavigationEndpoint5;
    }

    export interface LongBylineText2 {
        runs: Run8[];
    }

    export interface PublishedTimeText {
        simpleText: string;
    }

    export interface AccessibilityData2 {
        label: string;
    }

    export interface Accessibility2 {
        accessibilityData: AccessibilityData2;
    }

    export interface LengthText {
        accessibility: Accessibility2;
        simpleText: string;
    }

    export interface ViewCountText {
        simpleText: string;
    }

    export interface WebCommandMetadata7 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata7 {
        webCommandMetadata: WebCommandMetadata7;
    }

    export interface WatchEndpoint {
        videoId: string;
    }

    export interface NavigationEndpoint6 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata7;
        watchEndpoint: WatchEndpoint;
    }

    export interface AccessibilityData3 {
        label: string;
    }

    export interface MetadataBadgeRenderer2 {
        style: string;
        label: string;
        trackingParams: string;
        accessibilityData: AccessibilityData3;
    }

    export interface Badge {
        metadataBadgeRenderer: MetadataBadgeRenderer2;
    }

    export interface Icon2 {
        iconType: string;
    }

    export interface MetadataBadgeRenderer3 {
        icon: Icon2;
        style: string;
        tooltip: string;
        trackingParams: string;
    }

    export interface OwnerBadge2 {
        metadataBadgeRenderer: MetadataBadgeRenderer3;
    }

    export interface WebCommandMetadata8 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata8 {
        webCommandMetadata: WebCommandMetadata8;
    }

    export interface BrowseEndpoint5 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint7 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata8;
        browseEndpoint: BrowseEndpoint5;
    }

    export interface Run9 {
        text: string;
        navigationEndpoint: NavigationEndpoint7;
    }

    export interface OwnerText {
        runs: Run9[];
    }

    export interface WebCommandMetadata9 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata9 {
        webCommandMetadata: WebCommandMetadata9;
    }

    export interface BrowseEndpoint6 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint8 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata9;
        browseEndpoint: BrowseEndpoint6;
    }

    export interface Run10 {
        text: string;
        navigationEndpoint: NavigationEndpoint8;
    }

    export interface ShortBylineText2 {
        runs: Run10[];
    }

    export interface ShortViewCountText {
        simpleText: string;
    }

    export interface Run11 {
        text: string;
    }

    export interface Text2 {
        runs: Run11[];
    }

    export interface Icon3 {
        iconType: string;
    }

    export interface WebCommandMetadata10 {
        sendPost: boolean;
    }

    export interface CommandMetadata10 {
        webCommandMetadata: WebCommandMetadata10;
    }

    export interface WebCommandMetadata11 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata11 {
        webCommandMetadata: WebCommandMetadata11;
    }

    export interface CreatePlaylistServiceEndpoint {
        videoIds: string[];
        params: string;
    }

    export interface OnCreateListCommand {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata11;
        createPlaylistServiceEndpoint: CreatePlaylistServiceEndpoint;
    }

    export interface AddToPlaylistCommand {
        openMiniplayer: boolean;
        videoId: string;
        listType: string;
        onCreateListCommand: OnCreateListCommand;
        videoIds: string[];
    }

    export interface Action {
        clickTrackingParams: string;
        addToPlaylistCommand: AddToPlaylistCommand;
    }

    export interface SignalServiceEndpoint {
        signal: string;
        actions: Action[];
    }

    export interface ServiceEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata10;
        signalServiceEndpoint: SignalServiceEndpoint;
    }

    export interface MenuServiceItemRenderer {
        text: Text2;
        icon: Icon3;
        serviceEndpoint: ServiceEndpoint;
        trackingParams: string;
    }

    export interface Item2 {
        menuServiceItemRenderer: MenuServiceItemRenderer;
    }

    export interface AccessibilityData4 {
        label: string;
    }

    export interface Accessibility3 {
        accessibilityData: AccessibilityData4;
    }

    export interface MenuRenderer {
        items: Item2[];
        trackingParams: string;
        accessibility: Accessibility3;
    }

    export interface Menu {
        menuRenderer: MenuRenderer;
    }

    export interface Thumbnail6 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail5 {
        thumbnails: Thumbnail6[];
    }

    export interface WebCommandMetadata12 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata12 {
        webCommandMetadata: WebCommandMetadata12;
    }

    export interface BrowseEndpoint7 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint9 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata12;
        browseEndpoint: BrowseEndpoint7;
    }

    export interface AccessibilityData5 {
        label: string;
    }

    export interface Accessibility4 {
        accessibilityData: AccessibilityData5;
    }

    export interface ChannelThumbnailWithLinkRenderer {
        thumbnail: Thumbnail5;
        navigationEndpoint: NavigationEndpoint9;
        accessibility: Accessibility4;
    }

    export interface ChannelThumbnailSupportedRenderers {
        channelThumbnailWithLinkRenderer: ChannelThumbnailWithLinkRenderer;
    }

    export interface AccessibilityData6 {
        label: string;
    }

    export interface Accessibility5 {
        accessibilityData: AccessibilityData6;
    }

    export interface Text3 {
        accessibility: Accessibility5;
        simpleText: string;
    }

    export interface ThumbnailOverlayTimeStatusRenderer {
        text: Text3;
        style: string;
    }

    export interface UntoggledIcon {
        iconType: string;
    }

    export interface ToggledIcon {
        iconType: string;
    }

    export interface WebCommandMetadata13 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata13 {
        webCommandMetadata: WebCommandMetadata13;
    }

    export interface Action2 {
        addedVideoId: string;
        action: string;
    }

    export interface PlaylistEditEndpoint {
        playlistId: string;
        actions: Action2[];
    }

    export interface WebCommandMetadata14 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata14 {
        webCommandMetadata: WebCommandMetadata14;
    }

    export interface CreatePlaylistServiceEndpoint2 {
        videoIds: string[];
        params: string;
    }

    export interface OnCreateListCommand2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata14;
        createPlaylistServiceEndpoint: CreatePlaylistServiceEndpoint2;
    }

    export interface AddToPlaylistCommand2 {
        openMiniplayer: boolean;
        videoId: string;
        listType: string;
        onCreateListCommand: OnCreateListCommand2;
        videoIds: string[];
    }

    export interface Action3 {
        clickTrackingParams: string;
        addToPlaylistCommand: AddToPlaylistCommand2;
    }

    export interface SignalServiceEndpoint2 {
        signal: string;
        actions: Action3[];
    }

    export interface UntoggledServiceEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata13;
        playlistEditEndpoint: PlaylistEditEndpoint;
        signalServiceEndpoint: SignalServiceEndpoint2;
    }

    export interface WebCommandMetadata15 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata15 {
        webCommandMetadata: WebCommandMetadata15;
    }

    export interface Action4 {
        action: string;
        removedVideoId: string;
    }

    export interface PlaylistEditEndpoint2 {
        playlistId: string;
        actions: Action4[];
    }

    export interface ToggledServiceEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata15;
        playlistEditEndpoint: PlaylistEditEndpoint2;
    }

    export interface AccessibilityData7 {
        label: string;
    }

    export interface UntoggledAccessibility {
        accessibilityData: AccessibilityData7;
    }

    export interface AccessibilityData8 {
        label: string;
    }

    export interface ToggledAccessibility {
        accessibilityData: AccessibilityData8;
    }

    export interface ThumbnailOverlayToggleButtonRenderer {
        isToggled: boolean;
        untoggledIcon: UntoggledIcon;
        toggledIcon: ToggledIcon;
        untoggledTooltip: string;
        toggledTooltip: string;
        untoggledServiceEndpoint: UntoggledServiceEndpoint;
        toggledServiceEndpoint: ToggledServiceEndpoint;
        untoggledAccessibility: UntoggledAccessibility;
        toggledAccessibility: ToggledAccessibility;
        trackingParams: string;
    }

    export interface Run12 {
        text: string;
    }

    export interface Text4 {
        runs: Run12[];
    }

    export interface ThumbnailOverlayNowPlayingRenderer {
        text: Text4;
    }

    export interface ThumbnailOverlay {
        thumbnailOverlayTimeStatusRenderer: ThumbnailOverlayTimeStatusRenderer;
        thumbnailOverlayToggleButtonRenderer: ThumbnailOverlayToggleButtonRenderer;
        thumbnailOverlayNowPlayingRenderer: ThumbnailOverlayNowPlayingRenderer;
    }

    export interface VideoRenderer {
        videoId: string;
        thumbnail: Thumbnail3;
        title: Title3;
        descriptionSnippet: DescriptionSnippet2;
        longBylineText: LongBylineText2;
        publishedTimeText: PublishedTimeText;
        lengthText: LengthText;
        viewCountText: ViewCountText;
        navigationEndpoint: NavigationEndpoint6;
        badges: Badge[];
        ownerBadges: OwnerBadge2[];
        ownerText: OwnerText;
        shortBylineText: ShortBylineText2;
        trackingParams: string;
        showActionMenu: boolean;
        shortViewCountText: ShortViewCountText;
        menu: Menu;
        channelThumbnailSupportedRenderers: ChannelThumbnailSupportedRenderers;
        thumbnailOverlays: ThumbnailOverlay[];
    }

    export interface Item {
        videoRenderer: VideoRenderer;
    }

    export interface Run13 {
        text: string;
    }

    export interface AccessibilityData9 {
        label: string;
    }

    export interface Accessibility6 {
        accessibilityData: AccessibilityData9;
    }

    export interface CollapsedStateButtonText {
        runs: Run13[];
        accessibility: Accessibility6;
    }

    export interface VerticalListRenderer {
        items: Item[];
        collapsedItemCount: number;
        collapsedStateButtonText: CollapsedStateButtonText;
        trackingParams: string;
    }

    export interface Content3 {
        verticalListRenderer: VerticalListRenderer;
    }

    export interface ShelfRenderer {
        title: Title2;
        content: Content3;
        trackingParams: string;
    }

    export interface Thumbnail8 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail7 {
        thumbnails: Thumbnail8[];
    }

    export interface Run14 {
        text: string;
    }

    export interface AccessibilityData10 {
        label: string;
    }

    export interface Accessibility7 {
        accessibilityData: AccessibilityData10;
    }

    export interface Title4 {
        runs: Run14[];
        accessibility: Accessibility7;
    }

    export interface Run15 {
        text: string;
        bold?: boolean;
    }

    export interface DescriptionSnippet3 {
        runs: Run15[];
    }

    export interface WebCommandMetadata16 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata16 {
        webCommandMetadata: WebCommandMetadata16;
    }

    export interface BrowseEndpoint8 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint10 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata16;
        browseEndpoint: BrowseEndpoint8;
    }

    export interface Run16 {
        text: string;
        navigationEndpoint: NavigationEndpoint10;
    }

    export interface LongBylineText3 {
        runs: Run16[];
    }

    export interface PublishedTimeText2 {
        simpleText: string;
    }

    export interface AccessibilityData11 {
        label: string;
    }

    export interface Accessibility8 {
        accessibilityData: AccessibilityData11;
    }

    export interface LengthText2 {
        accessibility: Accessibility8;
        simpleText: string;
    }

    export interface ViewCountText2 {
        simpleText: string;
    }

    export interface WebCommandMetadata17 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata17 {
        webCommandMetadata: WebCommandMetadata17;
    }

    export interface WatchEndpoint2 {
        videoId: string;
        params: string;
    }

    export interface NavigationEndpoint11 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata17;
        watchEndpoint: WatchEndpoint2;
    }

    export interface Icon4 {
        iconType: string;
    }

    export interface MetadataBadgeRenderer4 {
        icon: Icon4;
        style: string;
        tooltip: string;
        trackingParams: string;
    }

    export interface OwnerBadge3 {
        metadataBadgeRenderer: MetadataBadgeRenderer4;
    }

    export interface WebCommandMetadata18 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata18 {
        webCommandMetadata: WebCommandMetadata18;
    }

    export interface BrowseEndpoint9 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint12 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata18;
        browseEndpoint: BrowseEndpoint9;
    }

    export interface Run17 {
        text: string;
        navigationEndpoint: NavigationEndpoint12;
    }

    export interface OwnerText2 {
        runs: Run17[];
    }

    export interface WebCommandMetadata19 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata19 {
        webCommandMetadata: WebCommandMetadata19;
    }

    export interface BrowseEndpoint10 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint13 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata19;
        browseEndpoint: BrowseEndpoint10;
    }

    export interface Run18 {
        text: string;
        navigationEndpoint: NavigationEndpoint13;
    }

    export interface ShortBylineText3 {
        runs: Run18[];
    }

    export interface ShortViewCountText2 {
        simpleText: string;
    }

    export interface Run19 {
        text: string;
    }

    export interface Text5 {
        runs: Run19[];
    }

    export interface Icon5 {
        iconType: string;
    }

    export interface WebCommandMetadata20 {
        sendPost: boolean;
    }

    export interface CommandMetadata20 {
        webCommandMetadata: WebCommandMetadata20;
    }

    export interface WebCommandMetadata21 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata21 {
        webCommandMetadata: WebCommandMetadata21;
    }

    export interface CreatePlaylistServiceEndpoint3 {
        videoIds: string[];
        params: string;
    }

    export interface OnCreateListCommand3 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata21;
        createPlaylistServiceEndpoint: CreatePlaylistServiceEndpoint3;
    }

    export interface AddToPlaylistCommand3 {
        openMiniplayer: boolean;
        videoId: string;
        listType: string;
        onCreateListCommand: OnCreateListCommand3;
        videoIds: string[];
    }

    export interface Action5 {
        clickTrackingParams: string;
        addToPlaylistCommand: AddToPlaylistCommand3;
    }

    export interface SignalServiceEndpoint3 {
        signal: string;
        actions: Action5[];
    }

    export interface ServiceEndpoint2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata20;
        signalServiceEndpoint: SignalServiceEndpoint3;
    }

    export interface MenuServiceItemRenderer2 {
        text: Text5;
        icon: Icon5;
        serviceEndpoint: ServiceEndpoint2;
        trackingParams: string;
    }

    export interface Item3 {
        menuServiceItemRenderer: MenuServiceItemRenderer2;
    }

    export interface AccessibilityData12 {
        label: string;
    }

    export interface Accessibility9 {
        accessibilityData: AccessibilityData12;
    }

    export interface MenuRenderer2 {
        items: Item3[];
        trackingParams: string;
        accessibility: Accessibility9;
    }

    export interface Menu2 {
        menuRenderer: MenuRenderer2;
    }

    export interface Thumbnail10 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail9 {
        thumbnails: Thumbnail10[];
    }

    export interface WebCommandMetadata22 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata22 {
        webCommandMetadata: WebCommandMetadata22;
    }

    export interface BrowseEndpoint11 {
        browseId: string;
        canonicalBaseUrl: string;
    }

    export interface NavigationEndpoint14 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata22;
        browseEndpoint: BrowseEndpoint11;
    }

    export interface AccessibilityData13 {
        label: string;
    }

    export interface Accessibility10 {
        accessibilityData: AccessibilityData13;
    }

    export interface ChannelThumbnailWithLinkRenderer2 {
        thumbnail: Thumbnail9;
        navigationEndpoint: NavigationEndpoint14;
        accessibility: Accessibility10;
    }

    export interface ChannelThumbnailSupportedRenderers2 {
        channelThumbnailWithLinkRenderer: ChannelThumbnailWithLinkRenderer2;
    }

    export interface AccessibilityData14 {
        label: string;
    }

    export interface Accessibility11 {
        accessibilityData: AccessibilityData14;
    }

    export interface Text6 {
        accessibility: Accessibility11;
        simpleText: string;
    }

    export interface ThumbnailOverlayTimeStatusRenderer2 {
        text: Text6;
        style: string;
    }

    export interface UntoggledIcon2 {
        iconType: string;
    }

    export interface ToggledIcon2 {
        iconType: string;
    }

    export interface WebCommandMetadata23 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata23 {
        webCommandMetadata: WebCommandMetadata23;
    }

    export interface Action6 {
        addedVideoId: string;
        action: string;
    }

    export interface PlaylistEditEndpoint3 {
        playlistId: string;
        actions: Action6[];
    }

    export interface WebCommandMetadata24 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata24 {
        webCommandMetadata: WebCommandMetadata24;
    }

    export interface CreatePlaylistServiceEndpoint4 {
        videoIds: string[];
        params: string;
    }

    export interface OnCreateListCommand4 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata24;
        createPlaylistServiceEndpoint: CreatePlaylistServiceEndpoint4;
    }

    export interface AddToPlaylistCommand4 {
        openMiniplayer: boolean;
        videoId: string;
        listType: string;
        onCreateListCommand: OnCreateListCommand4;
        videoIds: string[];
    }

    export interface Action7 {
        clickTrackingParams: string;
        addToPlaylistCommand: AddToPlaylistCommand4;
    }

    export interface SignalServiceEndpoint4 {
        signal: string;
        actions: Action7[];
    }

    export interface UntoggledServiceEndpoint2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata23;
        playlistEditEndpoint: PlaylistEditEndpoint3;
        signalServiceEndpoint: SignalServiceEndpoint4;
    }

    export interface WebCommandMetadata25 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata25 {
        webCommandMetadata: WebCommandMetadata25;
    }

    export interface Action8 {
        action: string;
        removedVideoId: string;
    }

    export interface PlaylistEditEndpoint4 {
        playlistId: string;
        actions: Action8[];
    }

    export interface ToggledServiceEndpoint2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata25;
        playlistEditEndpoint: PlaylistEditEndpoint4;
    }

    export interface AccessibilityData15 {
        label: string;
    }

    export interface UntoggledAccessibility2 {
        accessibilityData: AccessibilityData15;
    }

    export interface AccessibilityData16 {
        label: string;
    }

    export interface ToggledAccessibility2 {
        accessibilityData: AccessibilityData16;
    }

    export interface ThumbnailOverlayToggleButtonRenderer2 {
        isToggled: boolean;
        untoggledIcon: UntoggledIcon2;
        toggledIcon: ToggledIcon2;
        untoggledTooltip: string;
        toggledTooltip: string;
        untoggledServiceEndpoint: UntoggledServiceEndpoint2;
        toggledServiceEndpoint: ToggledServiceEndpoint2;
        untoggledAccessibility: UntoggledAccessibility2;
        toggledAccessibility: ToggledAccessibility2;
        trackingParams: string;
    }

    export interface Run20 {
        text: string;
    }

    export interface Text7 {
        runs: Run20[];
    }

    export interface ThumbnailOverlayNowPlayingRenderer2 {
        text: Text7;
    }

    export interface ThumbnailOverlay2 {
        thumbnailOverlayTimeStatusRenderer: ThumbnailOverlayTimeStatusRenderer2;
        thumbnailOverlayToggleButtonRenderer: ThumbnailOverlayToggleButtonRenderer2;
        thumbnailOverlayNowPlayingRenderer: ThumbnailOverlayNowPlayingRenderer2;
    }

    export interface MetadataBadgeRenderer5 {
        style: string;
        label: string;
        trackingParams: string;
    }

    export interface Badge2 {
        metadataBadgeRenderer: MetadataBadgeRenderer5;
    }

    export interface VideoRenderer2 {
        videoId: string;
        thumbnail: Thumbnail7;
        title: Title4;
        descriptionSnippet: DescriptionSnippet3;
        longBylineText: LongBylineText3;
        publishedTimeText: PublishedTimeText2;
        lengthText: LengthText2;
        viewCountText: ViewCountText2;
        navigationEndpoint: NavigationEndpoint11;
        ownerBadges: OwnerBadge3[];
        ownerText: OwnerText2;
        shortBylineText: ShortBylineText3;
        trackingParams: string;
        showActionMenu: boolean;
        shortViewCountText: ShortViewCountText2;
        menu: Menu2;
        channelThumbnailSupportedRenderers: ChannelThumbnailSupportedRenderers2;
        thumbnailOverlays: ThumbnailOverlay2[];
        badges: Badge2[];
    }

    export interface Thumbnail12 {
        url: string;
        width: number;
        height: number;
    }

    export interface Thumbnail11 {
        thumbnails: Thumbnail12[];
    }

    export interface Run21 {
        text: string;
    }

    export interface Query {
        runs: Run21[];
    }

    export interface WebCommandMetadata26 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata26 {
        webCommandMetadata: WebCommandMetadata26;
    }

    export interface SearchEndpoint3 {
        query: string;
        params: string;
    }

    export interface SearchEndpoint2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata26;
        searchEndpoint: SearchEndpoint3;
    }

    export interface SearchRefinementCardRenderer {
        thumbnail: Thumbnail11;
        query: Query;
        searchEndpoint: SearchEndpoint2;
        trackingParams: string;
    }

    export interface Card {
        searchRefinementCardRenderer: SearchRefinementCardRenderer;
    }

    export interface Run22 {
        text: string;
        bold?: boolean;
    }

    export interface Title5 {
        simpleText: string;
        runs: Run22[];
    }

    export interface Icon6 {
        iconType: string;
    }

    export interface RichListHeaderRenderer {
        title: Title5;
        trackingParams: string;
        icon: Icon6;
    }

    export interface Header {
        richListHeaderRenderer: RichListHeaderRenderer;
    }

    export interface Style {
        type: string;
    }

    export interface HorizontalCardListRenderer {
        cards: Card[];
        trackingParams: string;
        header: Header;
        style: Style;
    }

    export interface Content2 {
        channelRenderer: ChannelRenderer;
        shelfRenderer: ShelfRenderer;
        videoRenderer: VideoRenderer2;
        horizontalCardListRenderer: HorizontalCardListRenderer;
    }

    export interface ItemSectionRenderer {
        contents: Content2[];
        trackingParams: string;
    }

    export interface WebCommandMetadata27 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata27 {
        webCommandMetadata: WebCommandMetadata27;
    }

    export interface ContinuationCommand {
        token: string;
        request: string;
    }

    export interface ContinuationEndpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata27;
        continuationCommand: ContinuationCommand;
    }

    export interface ContinuationItemRenderer {
        trigger: string;
        continuationEndpoint: ContinuationEndpoint;
    }

    export interface Content {
        itemSectionRenderer: ItemSectionRenderer;
        continuationItemRenderer: ContinuationItemRenderer;
    }

    export interface Run23 {
        text: string;
    }

    export interface Title6 {
        runs: Run23[];
    }

    export interface Title7 {
        simpleText: string;
    }

    export interface Label {
        simpleText: string;
    }

    export interface WebCommandMetadata28 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata28 {
        webCommandMetadata: WebCommandMetadata28;
    }

    export interface SearchEndpoint4 {
        query: string;
        params: string;
    }

    export interface NavigationEndpoint15 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata28;
        searchEndpoint: SearchEndpoint4;
    }

    export interface SearchFilterRenderer {
        label: Label;
        navigationEndpoint: NavigationEndpoint15;
        tooltip: string;
        trackingParams: string;
        status: string;
    }

    export interface Filter {
        searchFilterRenderer: SearchFilterRenderer;
    }

    export interface SearchFilterGroupRenderer {
        title: Title7;
        filters: Filter[];
        trackingParams: string;
    }

    export interface Group {
        searchFilterGroupRenderer: SearchFilterGroupRenderer;
    }

    export interface Style2 {
        styleType: string;
    }

    export interface DefaultIcon {
        iconType: string;
    }

    export interface Run24 {
        text: string;
    }

    export interface DefaultText {
        runs: Run24[];
    }

    export interface Accessibility12 {
        label: string;
    }

    export interface ToggledStyle {
        styleType: string;
    }

    export interface AccessibilityData18 {
        label: string;
    }

    export interface AccessibilityData17 {
        accessibilityData: AccessibilityData18;
    }

    export interface ToggleButtonRenderer {
        style: Style2;
        isToggled: boolean;
        isDisabled: boolean;
        defaultIcon: DefaultIcon;
        defaultText: DefaultText;
        accessibility: Accessibility12;
        trackingParams: string;
        defaultTooltip: string;
        toggledTooltip: string;
        toggledStyle: ToggledStyle;
        accessibilityData: AccessibilityData17;
    }

    export interface Button {
        toggleButtonRenderer: ToggleButtonRenderer;
    }

    export interface SearchSubMenuRenderer {
        title: Title6;
        groups: Group[];
        trackingParams: string;
        button: Button;
    }

    export interface SubMenu {
        searchSubMenuRenderer: SearchSubMenuRenderer;
    }

    export interface SectionListRenderer {
        contents: Content[];
        trackingParams: string;
        subMenu: SubMenu;
        hideBottomSeparator: boolean;
        targetId: string;
    }

    export interface PrimaryContents {
        sectionListRenderer: SectionListRenderer;
    }

    export interface TwoColumnSearchResultsRenderer {
        primaryContents: PrimaryContents;
    }

    export interface Contents {
        twoColumnSearchResultsRenderer: TwoColumnSearchResultsRenderer;
    }

    export interface IconImage {
        iconType: string;
    }

    export interface Run25 {
        text: string;
    }

    export interface TooltipText {
        runs: Run25[];
    }

    export interface WebCommandMetadata29 {
        url: string;
        webPageType: string;
        rootVe: number;
        apiUrl: string;
    }

    export interface CommandMetadata29 {
        webCommandMetadata: WebCommandMetadata29;
    }

    export interface BrowseEndpoint12 {
        browseId: string;
    }

    export interface Endpoint {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata29;
        browseEndpoint: BrowseEndpoint12;
    }

    export interface TopbarLogoRenderer {
        iconImage: IconImage;
        tooltipText: TooltipText;
        endpoint: Endpoint;
        trackingParams: string;
    }

    export interface Logo {
        topbarLogoRenderer: TopbarLogoRenderer;
    }

    export interface Icon7 {
        iconType: string;
    }

    export interface Run26 {
        text: string;
    }

    export interface PlaceholderText {
        runs: Run26[];
    }

    export interface WebSearchboxConfig {
        requestLanguage: string;
        requestDomain: string;
        hasOnscreenKeyboard: boolean;
        focusSearchbox: boolean;
    }

    export interface Config {
        webSearchboxConfig: WebSearchboxConfig;
    }

    export interface WebCommandMetadata30 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata30 {
        webCommandMetadata: WebCommandMetadata30;
    }

    export interface SearchEndpoint6 {
        query: string;
    }

    export interface SearchEndpoint5 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata30;
        searchEndpoint: SearchEndpoint6;
    }

    export interface FusionSearchboxRenderer {
        icon: Icon7;
        placeholderText: PlaceholderText;
        config: Config;
        trackingParams: string;
        searchEndpoint: SearchEndpoint5;
    }

    export interface Searchbox {
        fusionSearchboxRenderer: FusionSearchboxRenderer;
    }

    export interface Icon8 {
        iconType: string;
    }

    export interface Icon9 {
        iconType: string;
    }

    export interface Run27 {
        text: string;
    }

    export interface Title8 {
        runs: Run27[];
    }

    export interface WebCommandMetadata31 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata31 {
        webCommandMetadata: WebCommandMetadata31;
    }

    export interface UrlEndpoint {
        url: string;
        target: string;
    }

    export interface NavigationEndpoint16 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata31;
        urlEndpoint: UrlEndpoint;
    }

    export interface CompactLinkRenderer {
        icon: Icon9;
        title: Title8;
        navigationEndpoint: NavigationEndpoint16;
        trackingParams: string;
    }

    export interface Item4 {
        compactLinkRenderer: CompactLinkRenderer;
    }

    export interface MultiPageMenuSectionRenderer {
        items: Item4[];
        trackingParams: string;
    }

    export interface Section {
        multiPageMenuSectionRenderer: MultiPageMenuSectionRenderer;
    }

    export interface MultiPageMenuRenderer {
        sections: Section[];
        trackingParams: string;
    }

    export interface MenuRenderer3 {
        multiPageMenuRenderer: MultiPageMenuRenderer;
    }

    export interface AccessibilityData19 {
        label: string;
    }

    export interface Accessibility13 {
        accessibilityData: AccessibilityData19;
    }

    export interface WebCommandMetadata32 {
        sendPost: boolean;
        apiUrl: string;
    }

    export interface CommandMetadata32 {
        webCommandMetadata: WebCommandMetadata32;
    }

    export interface MultiPageMenuRenderer2 {
        trackingParams: string;
        style: string;
        showLoadingSpinner: boolean;
    }

    export interface Popup {
        multiPageMenuRenderer: MultiPageMenuRenderer2;
    }

    export interface OpenPopupAction {
        popup: Popup;
        popupType: string;
        beReused: boolean;
    }

    export interface Action9 {
        clickTrackingParams: string;
        openPopupAction: OpenPopupAction;
    }

    export interface SignalServiceEndpoint5 {
        signal: string;
        actions: Action9[];
    }

    export interface MenuRequest {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata32;
        signalServiceEndpoint: SignalServiceEndpoint5;
    }

    export interface TopbarMenuButtonRenderer {
        icon: Icon8;
        menuRenderer: MenuRenderer3;
        trackingParams: string;
        accessibility: Accessibility13;
        tooltip: string;
        style: string;
        targetId: string;
        menuRequest: MenuRequest;
    }

    export interface Run28 {
        text: string;
    }

    export interface Text8 {
        runs: Run28[];
    }

    export interface Icon10 {
        iconType: string;
    }

    export interface WebCommandMetadata33 {
        url: string;
        webPageType: string;
        rootVe: number;
    }

    export interface CommandMetadata33 {
        webCommandMetadata: WebCommandMetadata33;
    }

    export interface SignInEndpoint2 {
        idamTag: string;
    }

    export interface NavigationEndpoint17 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata33;
        signInEndpoint: SignInEndpoint2;
    }

    export interface ButtonRenderer2 {
        style: string;
        size: string;
        text: Text8;
        icon: Icon10;
        navigationEndpoint: NavigationEndpoint17;
        trackingParams: string;
        targetId: string;
    }

    export interface TopbarButton {
        topbarMenuButtonRenderer: TopbarMenuButtonRenderer;
        buttonRenderer: ButtonRenderer2;
    }

    export interface Run29 {
        text: string;
    }

    export interface Title9 {
        runs: Run29[];
    }

    export interface Run30 {
        text: string;
    }

    export interface Title10 {
        runs: Run30[];
    }

    export interface Run31 {
        text: string;
    }

    export interface Label2 {
        runs: Run31[];
    }

    export interface AccessibilityData20 {
        label: string;
    }

    export interface HotkeyAccessibilityLabel {
        accessibilityData: AccessibilityData20;
    }

    export interface HotkeyDialogSectionOptionRenderer {
        label: Label2;
        hotkey: string;
        hotkeyAccessibilityLabel: HotkeyAccessibilityLabel;
    }

    export interface Option {
        hotkeyDialogSectionOptionRenderer: HotkeyDialogSectionOptionRenderer;
    }

    export interface HotkeyDialogSectionRenderer {
        title: Title10;
        options: Option[];
    }

    export interface Section2 {
        hotkeyDialogSectionRenderer: HotkeyDialogSectionRenderer;
    }

    export interface Run32 {
        text: string;
    }

    export interface Text9 {
        runs: Run32[];
    }

    export interface ButtonRenderer3 {
        style: string;
        size: string;
        isDisabled: boolean;
        text: Text9;
        trackingParams: string;
    }

    export interface DismissButton {
        buttonRenderer: ButtonRenderer3;
    }

    export interface HotkeyDialogRenderer {
        title: Title9;
        sections: Section2[];
        dismissButton: DismissButton;
        trackingParams: string;
    }

    export interface HotkeyDialog {
        hotkeyDialogRenderer: HotkeyDialogRenderer;
    }

    export interface WebCommandMetadata34 {
        sendPost: boolean;
    }

    export interface CommandMetadata34 {
        webCommandMetadata: WebCommandMetadata34;
    }

    export interface SignalAction {
        signal: string;
    }

    export interface Action10 {
        clickTrackingParams: string;
        signalAction: SignalAction;
    }

    export interface SignalServiceEndpoint6 {
        signal: string;
        actions: Action10[];
    }

    export interface Command {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata34;
        signalServiceEndpoint: SignalServiceEndpoint6;
    }

    export interface ButtonRenderer4 {
        trackingParams: string;
        command: Command;
    }

    export interface BackButton {
        buttonRenderer: ButtonRenderer4;
    }

    export interface WebCommandMetadata35 {
        sendPost: boolean;
    }

    export interface CommandMetadata35 {
        webCommandMetadata: WebCommandMetadata35;
    }

    export interface SignalAction2 {
        signal: string;
    }

    export interface Action11 {
        clickTrackingParams: string;
        signalAction: SignalAction2;
    }

    export interface SignalServiceEndpoint7 {
        signal: string;
        actions: Action11[];
    }

    export interface Command2 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata35;
        signalServiceEndpoint: SignalServiceEndpoint7;
    }

    export interface ButtonRenderer5 {
        trackingParams: string;
        command: Command2;
    }

    export interface ForwardButton {
        buttonRenderer: ButtonRenderer5;
    }

    export interface Run33 {
        text: string;
    }

    export interface Text10 {
        runs: Run33[];
    }

    export interface WebCommandMetadata36 {
        sendPost: boolean;
    }

    export interface CommandMetadata36 {
        webCommandMetadata: WebCommandMetadata36;
    }

    export interface SignalAction3 {
        signal: string;
    }

    export interface Action12 {
        clickTrackingParams: string;
        signalAction: SignalAction3;
    }

    export interface SignalServiceEndpoint8 {
        signal: string;
        actions: Action12[];
    }

    export interface Command3 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata36;
        signalServiceEndpoint: SignalServiceEndpoint8;
    }

    export interface ButtonRenderer6 {
        style: string;
        size: string;
        isDisabled: boolean;
        text: Text10;
        trackingParams: string;
        command: Command3;
    }

    export interface A11ySkipNavigationButton {
        buttonRenderer: ButtonRenderer6;
    }

    export interface WebCommandMetadata37 {
        sendPost: boolean;
    }

    export interface CommandMetadata37 {
        webCommandMetadata: WebCommandMetadata37;
    }

    export interface Run34 {
        text: string;
    }

    export interface PlaceholderHeader {
        runs: Run34[];
    }

    export interface Run35 {
        text: string;
    }

    export interface PromptHeader {
        runs: Run35[];
    }

    export interface Run36 {
        text: string;
    }

    export interface ExampleQuery1 {
        runs: Run36[];
    }

    export interface Run37 {
        text: string;
    }

    export interface ExampleQuery2 {
        runs: Run37[];
    }

    export interface Run38 {
        text: string;
    }

    export interface PromptMicrophoneLabel {
        runs: Run38[];
    }

    export interface Run39 {
        text: string;
    }

    export interface LoadingHeader {
        runs: Run39[];
    }

    export interface Run40 {
        text: string;
    }

    export interface ConnectionErrorHeader {
        runs: Run40[];
    }

    export interface Run41 {
        text: string;
    }

    export interface ConnectionErrorMicrophoneLabel {
        runs: Run41[];
    }

    export interface Run42 {
        text: string;
    }

    export interface PermissionsHeader {
        runs: Run42[];
    }

    export interface Run43 {
        text: string;
    }

    export interface PermissionsSubtext {
        runs: Run43[];
    }

    export interface Run44 {
        text: string;
    }

    export interface DisabledHeader {
        runs: Run44[];
    }

    export interface Run45 {
        text: string;
    }

    export interface DisabledSubtext {
        runs: Run45[];
    }

    export interface Icon11 {
        iconType: string;
    }

    export interface AccessibilityData22 {
        label: string;
    }

    export interface AccessibilityData21 {
        accessibilityData: AccessibilityData22;
    }

    export interface ButtonRenderer8 {
        style: string;
        size: string;
        isDisabled: boolean;
        icon: Icon11;
        trackingParams: string;
        accessibilityData: AccessibilityData21;
    }

    export interface ExitButton {
        buttonRenderer: ButtonRenderer8;
    }

    export interface Run46 {
        text: string;
    }

    export interface MicrophoneOffPromptHeader {
        runs: Run46[];
    }

    export interface VoiceSearchDialogRenderer {
        placeholderHeader: PlaceholderHeader;
        promptHeader: PromptHeader;
        exampleQuery1: ExampleQuery1;
        exampleQuery2: ExampleQuery2;
        promptMicrophoneLabel: PromptMicrophoneLabel;
        loadingHeader: LoadingHeader;
        connectionErrorHeader: ConnectionErrorHeader;
        connectionErrorMicrophoneLabel: ConnectionErrorMicrophoneLabel;
        permissionsHeader: PermissionsHeader;
        permissionsSubtext: PermissionsSubtext;
        disabledHeader: DisabledHeader;
        disabledSubtext: DisabledSubtext;
        exitButton: ExitButton;
        trackingParams: string;
        microphoneOffPromptHeader: MicrophoneOffPromptHeader;
    }

    export interface Popup2 {
        voiceSearchDialogRenderer: VoiceSearchDialogRenderer;
    }

    export interface OpenPopupAction2 {
        popup: Popup2;
        popupType: string;
    }

    export interface Action13 {
        clickTrackingParams: string;
        openPopupAction: OpenPopupAction2;
    }

    export interface SignalServiceEndpoint9 {
        signal: string;
        actions: Action13[];
    }

    export interface ServiceEndpoint3 {
        clickTrackingParams: string;
        commandMetadata: CommandMetadata37;
        signalServiceEndpoint: SignalServiceEndpoint9;
    }

    export interface Icon12 {
        iconType: string;
    }

    export interface AccessibilityData24 {
        label: string;
    }

    export interface AccessibilityData23 {
        accessibilityData: AccessibilityData24;
    }

    export interface ButtonRenderer7 {
        style: string;
        size: string;
        isDisabled: boolean;
        serviceEndpoint: ServiceEndpoint3;
        icon: Icon12;
        tooltip: string;
        trackingParams: string;
        accessibilityData: AccessibilityData23;
    }

    export interface VoiceSearchButton {
        buttonRenderer: ButtonRenderer7;
    }

    export interface DesktopTopbarRenderer {
        logo: Logo;
        searchbox: Searchbox;
        trackingParams: string;
        countryCode: string;
        topbarButtons: TopbarButton[];
        hotkeyDialog: HotkeyDialog;
        backButton: BackButton;
        forwardButton: ForwardButton;
        a11ySkipNavigationButton: A11ySkipNavigationButton;
        voiceSearchButton: VoiceSearchButton;
    }

    export interface Topbar {
        desktopTopbarRenderer: DesktopTopbarRenderer;
    }

    export interface AdSafetyReason {
    }

    export interface RootObject {
        responseContext: ResponseContext;
        estimatedResults: string;
        contents: Contents;
        trackingParams: string;
        topbar: Topbar;
        adSafetyReason: AdSafetyReason;
        refinements: string[];
    }

}
